/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    languageName: "English",
    // ── Hero Page ────────────────────────────
    heroHeadline1: "CREATE ANYTHING.",
    heroHeadline2: "MAKE EVERYTHING.",
    heroDesc: "The ultimate fusion of imagination and taste. Design things, craft recipes, and bring your ideas to life with the power of AI.",
    startCreating: "Start Creating",
    authenticating: "Authenticating…",
    thingMakerTitle: "Thing Maker",
    thingMakerDesc: "Design, build, invent and bring your ideas to reality.",
    enterWorkshop: "Enter Workshop",
    recipeMakerTitle: "Recipe Maker",
    recipeMakerDesc: "Create, mix, cook and craft delicious recipes.",
    enterKitchen: "Enter Kitchen",
    aiPowered: "AI POWERED",
    aiPoweredDesc: "Smart assistant to guide your every step.",
    endlessPoss: "ENDLESS POSSIBILITIES",
    endlessPossDesc: "From inventions to recipes, imagination has no limits.",
    saveOrg: "SAVE & ORGANISE",
    saveOrgDesc: "Store your creations and build your collection.",
    shareInspire: "SHARE & INSPIRE",
    shareInspireDesc: "Share your work and inspire the community.",
    meetAi: "Meet Your AI Assistant",
    recentCreations: "Recent Creations",
    quote: "Every great creation begins with an idea, and every delicious meal begins with a spark.",
    // ── Navbar ──────────────────────────────
    navHome: "Home",
    navThingMaker: "Thing Maker",
    navRecipeMaker: "Recipe Maker",
    navAiAssistant: "AI Assistant",
    navCollections: "Collections",
    navAbout: "About",
    myStudio: "My Studio",
    // ── Recipe Maker Page ───────────────────
    recipeMakerHeader: "RECIPE MAKER",
    recipeMakerSubtitle: "Kitchen",
    recipeMakerBannerDesc: "Turn your available ingredients into stunning culinary masterpieces. Our AI Chef intelligently analyses what you have, suggests the perfect recipe combinations, and guides you through every single step — from chopping and marinating to plating and garnishing. It's like having a world-class chef by your side, every time you cook.",
    newRecipe: "New Recipe",
    startCooking: "Start cooking",
    aiRecipeGenerator: "AI Recipe Generator",
    getSmartIdeas: "Get smart ideas",
    browsePantry: "Browse Pantry",
    hundredPlusIngredients: "100+ Ingredients",
    aiRecommendedRecipes: "AI Recommended Recipes For You",
    viewAll: "View all →",
    recipeInProgress: "Recipe In Progress",
    cookingNow: "Cooking Now",
    continueCooking: "Continue Cooking",
    ingredientsYouHave: "Ingredients You Have",
    managePantry: "Manage Pantry →",
    vegetables: "Vegetables",
    meats: "Meats",
    dairy: "Dairy",
    spices: "Spices",
    others: "Others",
    aiChefAssistant: "AI Chef Assistant",
    aiChefGreeting: "Hello Chef! I can suggest personalized recipes based on what's in your pantry, swap out ingredients you don't have, and guide you step-by-step so every dish turns out perfect — no culinary school required!",
    suggestRecipe: "Suggest a recipe with my ingredients",
    findSubstitute: "Help me find a substitute for eggs",
    pantryOverview: "Pantry Overview",
    mealPlan: "Meal Plan",
    today: "Today",
    tomorrow: "Tomorrow",
    nutritionInsights: "Nutrition Insights",
    // ── Thing Maker Page ────────────────────
    thingMakerHeader: "THING MAKER",
    thingMakerSubtitle: "Workshop",
    thingMakerBannerDesc: "Transform your raw materials and household scrap into brilliant, functional inventions. Our AI Workshop Planner analyses your available tools and materials, then generates a comprehensive, step-by-step project plan with safety guidelines, dimension estimates, and pro finishing tips — so every build feels professional from start to finish.",
    newProject: "New Project",
    startFromScratch: "Start from scratch",
    aiIdeaGenerator: "AI Idea Generator",
    getSmartSuggestions: "Get smart suggestions",
    importBlueprint: "Import Blueprint",
    requiresPro: "Requires Pro",
    aiSuggestedProjects: "AI Suggested Projects For You",
    myWorkbench: "My Workbench",
    currentProject: "Current Project",
    continueBuilding: "Continue Building",
    projectsBuilt: "Projects Built",
    inProgress: "In Progress",
    ideasSaved: "Ideas Saved",
    materialsInventory: "Materials Inventory",
    viewAllMaterials: "View All →",
    wood: "Wood",
    metal: "Metal",
    plastic: "Plastic",
    electronics: "Electronics",
    aiAssistantWidget: "AI Assistant",
    aiCreatorGreeting: "Hi Creator! I can help you design, plan, build and improve your inventions. Whether you're a total beginner or an experienced maker, I'll generate a complete project blueprint tailored to your exact materials and skill level — and keep you safe throughout the process!",
    suggestProjectMaterials: "Suggest a project with these materials",
    helpImproveDesign: "Help me improve this design",
    checkSafetyProject: "Check safety for my project",
    askAnything: "Ask anything about your project...",
    safetyFirst: "Safety First",
    useProtectiveGear: "Use protective gear",
    useProtectiveGearDesc: "Always wear safety gloves, goggles, and a dust mask when cutting, sanding, or drilling. Your hands and eyes are irreplaceable — protect them at every step.",
    checkToolConditions: "Check tool conditions",
    checkToolConditionsDesc: "Inspect every tool before use. Ensure blades are sharp, wires are not frayed, and handles are secure. A well-maintained tool is a safe tool.",
    workInSafeArea: "Work in a safe area",
    workInSafeAreaDesc: "Keep your workspace well-lit, clutter-free, and properly ventilated. Place a non-slip mat under your work surface and always have a first-aid kit nearby.",
    viewSafetyGuide: "View Safety Guide",
    // ── Thing Generator ─────────────────────
    thingGenTitle: "AI Project Blueprint Generator",
    thingGenDesc: "Describe your available scrap materials below and select your tools. Our AI will create a complete, step-by-step upcycling project plan tailored exactly to what you have on hand. From dimensions and materials list to assembly instructions and safety tips — your personalised blueprint is just one click away.",
    materialsPlaceholder: "Describe your materials (e.g., 2 cardboard boxes, 3 plastic bottles, old wire hangers…)",
    selectTools: "Select Your Tools",
    generateProject: "Generate Project Blueprint",
    generating: "Generating…",
    backToDashboard: "← Back to Dashboard",
    yourMaterials: "Your Materials",
    toolsAvailable: "Tools Available",
    difficulty: "Difficulty",
    estimatedTime: "Estimated Time",
    dimensions: "Dimensions",
    materialsRequired: "Materials Required",
    toolsUsed: "Tools Used",
    buildInstructions: "Step-by-Step Build Instructions",
    safetyGuidelines: "Safety Guidelines",
    watchTutorial: "Watch Tutorial on YouTube",
    saveProject: "Save Project",
    // ── Recipe Generator ────────────────────
    recipeGenTitle: "AI Recipe Creator",
    recipeGenDesc: "List the ingredients you currently have in your kitchen below. Our AI Chef will analyse your pantry, identify the best flavour combinations, and craft a complete, restaurant-quality recipe from scratch — including prep times, cooking steps, ingredient quantities, nutritional information, and even a YouTube tutorial recommendation so you can cook along visually.",
    ingredientsPlaceholder: "List your ingredients (e.g., chicken, garlic, lemon, olive oil, fresh basil, pasta…)",
    generateRecipe: "Generate My Recipe",
    generatingRecipe: "Crafting your recipe…",
    prepTime: "Prep Time",
    cookTime: "Cook Time",
    totalTime: "Total Time",
    servings: "Servings",
    ingredients: "Ingredients",
    instructions: "Step-by-Step Instructions",
    nutritionInfo: "Nutrition Information",
    healthScore: "Health Score",
    saveRecipe: "Save Recipe",
    // ── AI Assistant ────────────────────────
    aiAssistantTitle: "AI Assistant",
    aiAssistantSubtitle: "Ollama — Local Intelligence",
    aiGreeting: "Hi! I'm your local AI assistant. Ask me anything about cooking, kitchen swaps, crafting techniques, or material safety!",
    typeMessage: "Ask your AI assistant…",
    // ── About Page ──────────────────────────
    aboutTitle: "ABOUT CREAFORGE",
    aboutDesc: "Creaforge is the world's most intuitive AI-powered creativity platform — built for home chefs, DIY makers, students, and dreamers alike. Our mission is to eliminate the barrier between imagination and creation by providing an intelligent, beautifully designed toolkit that turns raw ingredients and scrap materials into masterpieces.",
    ourMission: "Our Mission",
    ourTech: "Our Technology",
    // ── Collections ─────────────────────────
    collectionsTitle: "My Collections",
    savedRecipes: "Saved Recipes",
    savedProjects: "Saved Projects",
    noSavedItems: "No saved items yet. Create something amazing!",
    // ── Magnificent Glass ────────────────────
    magnifyHint: "Hover over text to translate",
    magnifyLabel: "Language Lens",
  },

  hi: {
    languageName: "हिंदी",
    heroHeadline1: "कुछ भी बनाएं।",
    heroHeadline2: "सब कुछ बनाएं।",
    heroDesc: "कल्पना और स्वाद का अंतिम संगम। एआई की शक्ति के साथ चीजों को डिजाइन करें, स्वादिष्ट व्यंजन बनाएं और अपने विचारों को जीवंत करें।",
    startCreating: "बनाना शुरू करें",
    authenticating: "प्रमाणित किया जा रहा है...",
    thingMakerTitle: "थिंग मेकर",
    thingMakerDesc: "डिजाइन करें, बनाएं, आविष्कार करें और अपने विचारों को वास्तविकता में बदलें।",
    enterWorkshop: "वर्कशॉप में प्रवेश करें",
    recipeMakerTitle: "रेसिपी मेकर",
    recipeMakerDesc: "स्वादिष्ट व्यंजन बनाएं, मिलाएं और पकाएं।",
    enterKitchen: "रसोई में प्रवेश करें",
    aiPowered: "एआई संचालित",
    aiPoweredDesc: "आपके हर कदम का मार्गदर्शन करने के लिए स्मार्ट असिस्टेंट।",
    endlessPoss: "अनंत संभावनाएं",
    endlessPossDesc: "आविष्कारों से लेकर व्यंजनों तक, कल्पना की कोई सीमा नहीं है।",
    saveOrg: "सहेजें और व्यवस्थित करें",
    saveOrgDesc: "अपनी रचनाओं को स्टोर करें और अपना संग्रह बनाएं।",
    shareInspire: "साझा करें और प्रेरित करें",
    shareInspireDesc: "अपना काम साझा करें और समुदाय को प्रेरित करें।",
    meetAi: "अपने एआई असिस्टेंट से मिलें",
    recentCreations: "हाल की रचनाएँ",
    quote: "हर महान रचना एक विचार से शुरू होती है, और हर स्वादिष्ट भोजन एक चिंगारी से शुरू होता है।",
    navHome: "होम",
    navThingMaker: "थिंग मेकर",
    navRecipeMaker: "रेसिपी मेकर",
    navAiAssistant: "एआई असिस्टेंट",
    navCollections: "कलेक्शंस",
    navAbout: "हमारे बारे में",
    myStudio: "मेरा स्टूडियो",
    recipeMakerHeader: "रेसिपी मेकर",
    recipeMakerSubtitle: "रसोईघर",
    recipeMakerBannerDesc: "अपने उपलब्ध सामग्री को शानदार पाक कृतियों में बदलें। हमारा एआई शेफ बुद्धिमानी से विश्लेषण करता है कि आपके पास क्या है, सही रेसिपी संयोजन सुझाता है, और आपको हर एक कदम — काटने और मैरीनेट करने से लेकर परोसने और सजाने तक — में मार्गदर्शन करता है। यह जैसे आपके पास एक विश्व स्तरीय शेफ हो, हर बार जब आप खाना बनाएं।",
    newRecipe: "नई रेसिपी",
    startCooking: "पकाना शुरू करें",
    aiRecipeGenerator: "एआई रेसिपी जनरेटर",
    getSmartIdeas: "स्मार्ट आइडिया पाएं",
    browsePantry: "पेंट्री देखें",
    hundredPlusIngredients: "100+ सामग्री",
    aiRecommendedRecipes: "आपके लिए एआई अनुशंसित रेसिपी",
    viewAll: "सभी देखें →",
    recipeInProgress: "प्रगति में रेसिपी",
    cookingNow: "अभी पका रहे हैं",
    continueCooking: "खाना बनाना जारी रखें",
    ingredientsYouHave: "आपके पास उपलब्ध सामग्री",
    managePantry: "पेंट्री प्रबंधित करें →",
    vegetables: "सब्जियां",
    meats: "मांस",
    dairy: "डेयरी",
    spices: "मसाले",
    others: "अन्य",
    aiChefAssistant: "एआई शेफ असिस्टेंट",
    aiChefGreeting: "नमस्ते शेफ! मैं आपकी पेंट्री में जो है उसके आधार पर व्यक्तिगत रेसिपी सुझा सकता हूं, जो सामग्री आपके पास नहीं है उसे बदल सकता हूं, और हर कदम पर मार्गदर्शन कर सकता हूं ताकि हर व्यंजन एकदम सही बने — किसी पाककला स्कूल की जरूरत नहीं!",
    suggestRecipe: "मेरी सामग्री से रेसिपी सुझाएं",
    findSubstitute: "अंडे का विकल्प खोजने में मदद करें",
    pantryOverview: "पेंट्री अवलोकन",
    mealPlan: "भोजन योजना",
    today: "आज",
    tomorrow: "कल",
    nutritionInsights: "पोषण जानकारी",
    thingMakerHeader: "थिंग मेकर",
    thingMakerSubtitle: "वर्कशॉप",
    thingMakerBannerDesc: "अपने कच्चे माल और घरेलू स्क्रैप को शानदार, कार्यात्मक आविष्कारों में बदलें। हमारा एआई वर्कशॉप प्लानर आपके उपलब्ध टूल और सामग्री का विश्लेषण करता है, फिर सुरक्षा दिशानिर्देशों, आयाम अनुमानों और प्रो फिनिशिंग टिप्स के साथ एक व्यापक, चरण-दर-चरण प्रोजेक्ट योजना तैयार करता है — ताकि हर निर्माण शुरू से अंत तक पेशेवर महसूस हो।",
    newProject: "नया प्रोजेक्ट",
    startFromScratch: "शुरू से शुरू करें",
    aiIdeaGenerator: "एआई आइडिया जनरेटर",
    getSmartSuggestions: "स्मार्ट सुझाव पाएं",
    importBlueprint: "ब्लूप्रिंट इम्पोर्ट करें",
    requiresPro: "प्रो की आवश्यकता है",
    aiSuggestedProjects: "आपके लिए एआई सुझाए गए प्रोजेक्ट",
    myWorkbench: "मेरी वर्कबेंच",
    currentProject: "वर्तमान प्रोजेक्ट",
    continueBuilding: "बनाना जारी रखें",
    projectsBuilt: "बने प्रोजेक्ट",
    inProgress: "प्रगति में",
    ideasSaved: "सहेजे गए विचार",
    materialsInventory: "सामग्री सूची",
    viewAllMaterials: "सभी देखें →",
    wood: "लकड़ी",
    metal: "धातु",
    plastic: "प्लास्टिक",
    electronics: "इलेक्ट्रॉनिक्स",
    aiAssistantWidget: "एआई असिस्टेंट",
    aiCreatorGreeting: "नमस्ते निर्माता! मैं आपको अपने आविष्कारों को डिजाइन करने, योजना बनाने, बनाने और सुधारने में मदद कर सकता हूं। चाहे आप पूर्ण शुरुआती हों या अनुभवी निर्माता, मैं आपकी सटीक सामग्री और कौशल स्तर के अनुसार एक पूर्ण प्रोजेक्ट ब्लूप्रिंट तैयार करूंगा — और पूरी प्रक्रिया में आपको सुरक्षित रखूंगा!",
    suggestProjectMaterials: "इन सामग्रियों से प्रोजेक्ट सुझाएं",
    helpImproveDesign: "इस डिजाइन को बेहतर बनाने में मदद करें",
    checkSafetyProject: "मेरे प्रोजेक्ट के लिए सुरक्षा जांचें",
    askAnything: "अपने प्रोजेक्ट के बारे में कुछ भी पूछें...",
    safetyFirst: "सुरक्षा पहले",
    useProtectiveGear: "सुरक्षात्मक गियर का उपयोग करें",
    useProtectiveGearDesc: "काटते, रेतते या ड्रिल करते समय हमेशा सुरक्षा दस्ताने, चश्मा और धूल मास्क पहनें। आपके हाथ और आंखें अमूल्य हैं — हर कदम पर उनकी रक्षा करें।",
    checkToolConditions: "टूल की स्थिति जांचें",
    checkToolConditionsDesc: "उपयोग से पहले हर टूल की जांच करें। सुनिश्चित करें कि ब्लेड तेज हैं, तार टूटे नहीं हैं और हैंडल सुरक्षित हैं। एक अच्छी तरह से रखरखाव किया गया टूल एक सुरक्षित टूल है।",
    workInSafeArea: "सुरक्षित क्षेत्र में काम करें",
    workInSafeAreaDesc: "अपने कार्यक्षेत्र को अच्छी तरह से रोशन, साफ और उचित हवादार रखें। काम की सतह के नीचे एक नॉन-स्लिप मैट रखें और हमेशा प्राथमिक चिकित्सा किट पास में रखें।",
    viewSafetyGuide: "सुरक्षा गाइड देखें",
    thingGenTitle: "एआई प्रोजेक्ट ब्लूप्रिंट जनरेटर",
    thingGenDesc: "नीचे अपनी उपलब्ध स्क्रैप सामग्री का वर्णन करें और अपने टूल चुनें। हमारा एआई आपके पास उपलब्ध चीजों के अनुसार एक पूर्ण, चरण-दर-चरण अपसाइकलिंग प्रोजेक्ट योजना बनाएगा। आयाम और सामग्री सूची से लेकर असेंबली निर्देश और सुरक्षा युक्तियों तक — आपका व्यक्तिगत ब्लूप्रिंट बस एक क्लिक दूर है।",
    materialsPlaceholder: "अपनी सामग्री का वर्णन करें (उदा., 2 कार्डबोर्ड बॉक्स, 3 प्लास्टिक बोतलें, पुराने तार हैंगर…)",
    selectTools: "अपने टूल चुनें",
    generateProject: "प्रोजेक्ट ब्लूप्रिंट तैयार करें",
    generating: "तैयार हो रहा है…",
    backToDashboard: "← डैशबोर्ड पर वापस",
    yourMaterials: "आपकी सामग्री",
    toolsAvailable: "उपलब्ध टूल",
    difficulty: "कठिनाई",
    estimatedTime: "अनुमानित समय",
    dimensions: "आयाम",
    materialsRequired: "आवश्यक सामग्री",
    toolsUsed: "उपयोग किए गए टूल",
    buildInstructions: "चरण-दर-चरण निर्माण निर्देश",
    safetyGuidelines: "सुरक्षा दिशानिर्देश",
    watchTutorial: "यूट्यूब पर ट्यूटोरियल देखें",
    saveProject: "प्रोजेक्ट सहेजें",
    recipeGenTitle: "एआई रेसिपी क्रिएटर",
    recipeGenDesc: "नीचे अपनी रसोई में वर्तमान में उपलब्ध सामग्री की सूची बनाएं। हमारा एआई शेफ आपकी पेंट्री का विश्लेषण करेगा, सर्वोत्तम स्वाद संयोजन पहचानेगा, और शुरू से एक पूर्ण, रेस्तरां गुणवत्ता की रेसिपी बनाएगा — जिसमें तैयारी का समय, खाना पकाने के चरण, सामग्री की मात्रा, पोषण संबंधी जानकारी, और एक यूट्यूब ट्यूटोरियल की सिफारिश भी शामिल है।",
    ingredientsPlaceholder: "अपनी सामग्री सूचीबद्ध करें (उदा., चिकन, लहसुन, नींबू, जैतून का तेल, ताजा तुलसी, पास्ता…)",
    generateRecipe: "मेरी रेसिपी तैयार करें",
    generatingRecipe: "आपकी रेसिपी तैयार हो रही है…",
    prepTime: "तैयारी का समय",
    cookTime: "पकाने का समय",
    totalTime: "कुल समय",
    servings: "परोसने वाले",
    ingredients: "सामग्री",
    instructions: "चरण-दर-चरण निर्देश",
    nutritionInfo: "पोषण जानकारी",
    healthScore: "स्वास्थ्य स्कोर",
    saveRecipe: "रेसिपी सहेजें",
    aiAssistantTitle: "एआई असिस्टेंट",
    aiAssistantSubtitle: "ओलामा — स्थानीय बुद्धिमत्ता",
    aiGreeting: "नमस्ते! मैं आपका स्थानीय एआई असिस्टेंट हूं। खाना पकाने, रसोई स्वैप, शिल्प तकनीकों या सामग्री सुरक्षा के बारे में कुछ भी पूछें!",
    typeMessage: "अपने एआई असिस्टेंट से पूछें…",
    aboutTitle: "क्रिएफोर्ज के बारे में",
    aboutDesc: "क्रिएफोर्ज दुनिया का सबसे सहज एआई-संचालित रचनात्मकता प्लेटफॉर्म है — घर के शेफ, डीआईवाई निर्माताओं, छात्रों और सपने देखने वालों के लिए बनाया गया।",
    ourMission: "हमारा मिशन",
    ourTech: "हमारी तकनीक",
    collectionsTitle: "मेरे संग्रह",
    savedRecipes: "सहेजी गई रेसिपी",
    savedProjects: "सहेजे गए प्रोजेक्ट",
    noSavedItems: "अभी तक कोई सहेजी गई वस्तु नहीं। कुछ अद्भुत बनाएं!",
    magnifyHint: "अनुवाद करने के लिए टेक्स्ट पर होवर करें",
    magnifyLabel: "भाषा लेंस",
  },

  te: {
    languageName: "తెలుగు",
    heroHeadline1: "ఏదైనా సృష్టించండి.",
    heroHeadline2: "ప్రతిదీ తయారు చేయండి.",
    heroDesc: "ఊహ మరియు రుచి యొక్క అంతిమ కలయిక. వస్తువులను డిజైన్ చేయండి, వంటకాలను రూపొందించండి మరియు AI శక్తితో మీ ఆలోచనలకు జీవం పోయండి.",
    startCreating: "సృష్టించడం ప్రారంభించండి",
    authenticating: "ధృవీకరిస్తోంది...",
    thingMakerTitle: "థింగ్ మేకర్",
    thingMakerDesc: "డిజైన్ చేయండి, నిర్మించండి, కనుగొనండి మరియు మీ ఆలోచనలను నిజం చేసుకోండి.",
    enterWorkshop: "వర్క్‌షాప్‌లోకి ప్రవేశించండి",
    recipeMakerTitle: "రెసిపీ మేకర్",
    recipeMakerDesc: "రుచికరమైన వంటకాలను సృష్టించండి, కలపండి మరియు వండండి.",
    enterKitchen: "కిచెన్‌లోకి ప్రవేశించండి",
    aiPowered: "AI పవర్డ్",
    aiPoweredDesc: "మీ ప్రతి అడుగును మార్గనిర్దేశం చేసే స్మార్ట్ అసిస్టెంట్.",
    endlessPoss: "అనంతమైన అవకాశాలు",
    endlessPossDesc: "ఆవిష్కరణల నుండి వంటకాల వరకు, ఊహకు హద్దులు లేవు.",
    saveOrg: "సేవ్ మరియు ఆర్గనైజ్",
    saveOrgDesc: "మీ సృష్టిని నిల్వ చేయండి మరియు మీ సేకరణను రూపొందించండి.",
    shareInspire: "షేర్ & ఇన్‌స్పైర్",
    shareInspireDesc: "మీ పనిని పంచుకోండి మరియు కమ్యూనిటీని ప్రేరేపించండి.",
    meetAi: "మీ AI అసిస్టెంట్‌ని కలవండి",
    recentCreations: "ఇటీవలి సృష్టిలు",
    quote: "ప్రతి గొప్ప సృష్టి ఒక ఆలోచనతో ప్రారంభమవుతుంది మరియు ప్రతి రుచికరమైన భోజనం ఒక స్పార్క్‌తో ప్రారంభమవుతుంది.",
    navHome: "హోమ్",
    navThingMaker: "థింగ్ మేకర్",
    navRecipeMaker: "రెసిపీ మేకర్",
    navAiAssistant: "AI అసిస్టెంట్",
    navCollections: "కలెక్షన్స్",
    navAbout: "మా గురించి",
    myStudio: "నా స్టూడియో",
    recipeMakerHeader: "రెసిపీ మేకర్",
    recipeMakerSubtitle: "వంటగది",
    recipeMakerBannerDesc: "మీ అందుబాటులో ఉన్న పదార్థాలను అద్భుతమైన పాక కళా ఖండాలుగా మార్చండి. మా AI షెఫ్ మీ దగ్గర ఏమి ఉందో తెలివిగా విశ్లేషిస్తాడు, సరైన రెసిపీ కలయికలను సూచిస్తాడు, మరియు కత్తిరించడం మరియు మేరినేట్ చేయడం నుండి అందంగా పెట్టడం వరకు ప్రతి అడుగులో మీకు మార్గనిర్దేశం చేస్తాడు.",
    newRecipe: "కొత్త రెసిపీ",
    startCooking: "వండటం ప్రారంభించండి",
    aiRecipeGenerator: "AI రెసిపీ జనరేటర్",
    getSmartIdeas: "స్మార్ట్ ఆలోచనలు పొందండి",
    browsePantry: "పాంట్రీ చూడండి",
    hundredPlusIngredients: "100+ పదార్థాలు",
    aiRecommendedRecipes: "మీ కోసం AI సిఫార్సు చేసిన రెసిపీలు",
    viewAll: "అన్నీ చూడండి →",
    recipeInProgress: "ప్రగతిలో ఉన్న రెసిపీ",
    cookingNow: "ఇప్పుడు వండుతున్నారు",
    continueCooking: "వండటం కొనసాగించండి",
    ingredientsYouHave: "మీ దగ్గర ఉన్న పదార్థాలు",
    managePantry: "పాంట్రీ నిర్వహించండి →",
    vegetables: "కూరగాయలు",
    meats: "మాంసం",
    dairy: "పాల పదార్థాలు",
    spices: "సుగంధ ద్రవ్యాలు",
    others: "ఇతరాలు",
    aiChefAssistant: "AI షెఫ్ అసిస్టెంట్",
    aiChefGreeting: "నమస్కారం షెఫ్! మీ పాంట్రీలో ఏమి ఉందో దాని ఆధారంగా నేను వ్యక్తిగతీకరించిన రెసిపీలను సూచించగలను, మీ దగ్గర లేని పదార్థాలను మార్చగలను, మరియు ప్రతి అడుగులో మార్గనిర్దేశం చేయగలను.",
    suggestRecipe: "నా పదార్థాలతో రెసిపీ సూచించండి",
    findSubstitute: "గుడ్లకు ప్రత్యామ్నాయం కనుగొనడంలో సహాయం చేయండి",
    pantryOverview: "పాంట్రీ అవలోకనం",
    mealPlan: "భోజన ప్రణాళిక",
    today: "ఈరోజు",
    tomorrow: "రేపు",
    nutritionInsights: "పోషణ సమాచారం",
    thingMakerHeader: "థింగ్ మేకర్",
    thingMakerSubtitle: "వర్క్‌షాప్",
    thingMakerBannerDesc: "మీ ముడి పదార్థాలు మరియు గృహ స్క్రాప్‌ను అద్భుతమైన, పనికి వచ్చే ఆవిష్కరణలుగా మార్చండి. మా AI వర్క్‌షాప్ ప్లానర్ మీ అందుబాటులో ఉన్న సాధనాలు మరియు పదార్థాలను విశ్లేషించి, భద్రతా మార్గదర్శకాలు, కొలత అంచనాలు మరియు ప్రో ఫినిషింగ్ చిట్కాలతో సమగ్ర దశల వారీ ప్రాజెక్ట్ ప్లాన్ రూపొందిస్తుంది.",
    newProject: "కొత్త ప్రాజెక్ట్",
    startFromScratch: "మొదటి నుండి ప్రారంభించండి",
    aiIdeaGenerator: "AI ఆలోచన జనరేటర్",
    getSmartSuggestions: "స్మార్ట్ సూచనలు పొందండి",
    importBlueprint: "బ్లూప్రింట్ దిగుమతి చేయండి",
    requiresPro: "ప్రో అవసరం",
    aiSuggestedProjects: "మీ కోసం AI సూచించిన ప్రాజెక్టులు",
    myWorkbench: "నా వర్క్‌బెంచ్",
    currentProject: "ప్రస్తుత ప్రాజెక్ట్",
    continueBuilding: "నిర్మించడం కొనసాగించండి",
    projectsBuilt: "నిర్మించిన ప్రాజెక్టులు",
    inProgress: "ప్రగతిలో",
    ideasSaved: "సేవ్ చేసిన ఆలోచనలు",
    materialsInventory: "పదార్థాల జాబితా",
    viewAllMaterials: "అన్నీ చూడండి →",
    wood: "చెక్క",
    metal: "లోహం",
    plastic: "ప్లాస్టిక్",
    electronics: "ఎలక్ట్రానిక్స్",
    aiAssistantWidget: "AI అసిస్టెంట్",
    aiCreatorGreeting: "నమస్కారం సృష్టికర్తా! మీ ఆవిష్కరణలను డిజైన్ చేయడంలో, ప్లాన్ చేయడంలో, నిర్మించడంలో మరియు మెరుగుపరచడంలో నేను సహాయం చేయగలను.",
    suggestProjectMaterials: "ఈ పదార్థాలతో ప్రాజెక్ట్ సూచించండి",
    helpImproveDesign: "ఈ డిజైన్‌ను మెరుగుపరచడంలో సహాయం చేయండి",
    checkSafetyProject: "నా ప్రాజెక్ట్ కోసం భద్రత తనిఖీ చేయండి",
    askAnything: "మీ ప్రాజెక్ట్ గురించి ఏదైనా అడగండి...",
    safetyFirst: "భద్రత మొదట",
    useProtectiveGear: "రక్షణ గేర్ ఉపయోగించండి",
    useProtectiveGearDesc: "కత్తిరించేటప్పుడు, నునుమ చేసేటప్పుడు లేదా డ్రిల్ చేసేటప్పుడు ఎల్లప్పుడూ భద్రతా చేతి తొడుగులు, కళ్ళద్దాలు మరియు ధూళి మాస్క్ ధరించండి.",
    checkToolConditions: "సాధన స్థితి తనిఖీ చేయండి",
    checkToolConditionsDesc: "ఉపయోగించే ముందు ప్రతి సాధనాన్ని తనిఖీ చేయండి. బ్లేడ్‌లు పదునుగా ఉన్నాయో, తీగలు తెగలేదో, హ్యాండిల్‌లు సురక్షితంగా ఉన్నాయో నిర్ధారించుకోండి.",
    workInSafeArea: "సురక్షిత ప్రాంతంలో పని చేయండి",
    workInSafeAreaDesc: "మీ కార్యాలయాన్ని చక్కగా వెలిగించి, పరిష్కారంగా మరియు సరిగ్గా వెంటిలేటెడ్‌గా ఉంచండి.",
    viewSafetyGuide: "భద్రతా మార్గదర్శిని చూడండి",
    thingGenTitle: "AI ప్రాజెక్ట్ బ్లూప్రింట్ జనరేటర్",
    thingGenDesc: "దిగువ మీ అందుబాటులో ఉన్న స్క్రాప్ పదార్థాలను వివరించండి మరియు మీ సాధనాలను ఎంచుకోండి. మీ దగ్గర అందుబాటులో ఉన్న వాటికి అనుగుణంగా సమగ్ర, దశల వారీ అప్‌సైక్లింగ్ ప్రాజెక్ట్ ప్లాన్ రూపొందిస్తాం.",
    materialsPlaceholder: "మీ పదార్థాలను వివరించండి (ఉదా., 2 కార్డ్‌బోర్డ్ బాక్సులు, 3 ప్లాస్టిక్ బాటిళ్ళు, పాత వైర్ హ్యాంగర్లు…)",
    selectTools: "మీ సాధనాలు ఎంచుకోండి",
    generateProject: "ప్రాజెక్ట్ బ్లూప్రింట్ రూపొందించండి",
    generating: "రూపొందిస్తోంది…",
    backToDashboard: "← డాష్‌బోర్డ్‌కు తిరిగి",
    yourMaterials: "మీ పదార్థాలు",
    toolsAvailable: "అందుబాటులో ఉన్న సాధనాలు",
    difficulty: "కష్టం",
    estimatedTime: "అంచనా సమయం",
    dimensions: "పరిమాణాలు",
    materialsRequired: "అవసరమైన పదార్థాలు",
    toolsUsed: "ఉపయోగించిన సాధనాలు",
    buildInstructions: "దశల వారీ నిర్మాణ సూచనలు",
    safetyGuidelines: "భద్రతా మార్గదర్శకాలు",
    watchTutorial: "YouTube లో ట్యుటోరియల్ చూడండి",
    saveProject: "ప్రాజెక్ట్ సేవ్ చేయండి",
    recipeGenTitle: "AI రెసిపీ క్రియేటర్",
    recipeGenDesc: "మీ వంటగదిలో ప్రస్తుతం అందుబాటులో ఉన్న పదార్థాల జాబితాను దిగువ చేర్చండి. మా AI షెఫ్ మీ పాంట్రీని విశ్లేషించి, ఉత్తమ రుచి సంయోజనాలను గుర్తించి, సంపూర్ణ రెస్టారెంట్ నాణ్యత రెసిపీని రూపొందిస్తాడు.",
    ingredientsPlaceholder: "మీ పదార్థాలు జాబితా చేయండి (ఉదా., చికెన్, వెల్లుల్లి, నిమ్మ, ఆలివ్ ఆయిల్, తాజా బేసిల్, పాస్తా…)",
    generateRecipe: "నా రెసిపీ రూపొందించండి",
    generatingRecipe: "మీ రెసిపీ తయారవుతోంది…",
    prepTime: "తయారీ సమయం",
    cookTime: "వంట సమయం",
    totalTime: "మొత్తం సమయం",
    servings: "వడ్డించే వ్యక్తులు",
    ingredients: "పదార్థాలు",
    instructions: "దశల వారీ సూచనలు",
    nutritionInfo: "పోషణ సమాచారం",
    healthScore: "ఆరోగ్య స్కోర్",
    saveRecipe: "రెసిపీ సేవ్ చేయండి",
    aiAssistantTitle: "AI అసిస్టెంట్",
    aiAssistantSubtitle: "ఒల్లామా — స్థానిక తెలివి",
    aiGreeting: "నమస్కారం! నేను మీ స్థానిక AI అసిస్టెంట్‌ని. వంట, వంటగది స్వాప్‌లు, క్రాఫ్టింగ్ పద్ధతులు లేదా పదార్థ భద్రత గురించి ఏదైనా అడగండి!",
    typeMessage: "మీ AI అసిస్టెంట్‌కు అడగండి…",
    aboutTitle: "క్రియాఫోర్జ్ గురించి",
    aboutDesc: "క్రియాఫోర్జ్ అనేది ప్రపంచంలోనే అత్యంత సహజమైన AI-ఆధారిత సృజనాత్మకత వేదిక.",
    ourMission: "మా లక్ష్యం",
    ourTech: "మా సాంకేతికత",
    collectionsTitle: "నా సేకరణలు",
    savedRecipes: "సేవ్ చేసిన రెసిపీలు",
    savedProjects: "సేవ్ చేసిన ప్రాజెక్టులు",
    noSavedItems: "ఇంకా సేవ్ చేసిన అంశాలు లేవు. అద్భుతమైనదేదైనా సృష్టించండి!",
    magnifyHint: "అనువదించడానికి టెక్స్ట్‌పై హోవర్ చేయండి",
    magnifyLabel: "భాష లెన్స్",
  },

  ta: {
    languageName: "தமிழ்",
    heroHeadline1: "எதையும் உருவாக்குங்கள்.",
    heroHeadline2: "அனைத்தையும் உருவாக்குங்கள்.",
    heroDesc: "கற்பனை மற்றும் சுவையின் இறுதி கலவை. பொருட்களை வடிவமைக்கவும், சமையல் குறிப்புகளை உருவாக்கவும், AI-யின் சக்தியால் உங்கள் யோசனைகளை உயிர்ப்பிக்கவும்.",
    startCreating: "உருவாக்கத் தொடங்குங்கள்",
    authenticating: "அங்கீகரிக்கப்படுகிறது...",
    thingMakerTitle: "திங் மேக்கர்",
    thingMakerDesc: "வடிவமைக்கவும், உருவாக்கவும், கண்டுபிடிக்கவும் மற்றும் உங்கள் யோசனைகளை நனவாக்கவும்.",
    enterWorkshop: "பட்டறையில் நுழையுங்கள்",
    recipeMakerTitle: "ரெசிபி மேக்கர்",
    recipeMakerDesc: "சுவையான சமையல் குறிப்புகளை உருவாக்கவும், கலக்கவும், சமைக்கவும்.",
    enterKitchen: "சமையலறையில் நுழையுங்கள்",
    aiPowered: "AI இயக்கப்படுகிறது",
    aiPoweredDesc: "உங்கள் ஒவ்வொரு அடியையும் வழிநடத்த ஸ்மார்ட் உதவியாளர்.",
    endlessPoss: "முடிவற்ற சாத்தியங்கள்",
    endlessPossDesc: "கண்டுபிடிப்புகள் முதல் சமையல் குறிப்புகள் வரை, கற்பனைக்கு எல்லையே இல்லை.",
    saveOrg: "சேமி & ஒழுங்கமை",
    saveOrgDesc: "உங்கள் படைப்புகளைச் சேமித்து உங்கள் சேகரிப்பை உருவாக்குங்கள்.",
    shareInspire: "பகிர்ந்து ஊக்குவிக்கவும்",
    shareInspireDesc: "உங்கள் வேலையைப் பகிர்ந்து சமூகத்தை ஊக்குவிக்கவும்.",
    meetAi: "உங்கள் AI உதவியாளரைச் சந்திக்கவும்",
    recentCreations: "சமீபத்திய படைப்புகள்",
    quote: "ஒவ்வொரு சிறந்த படைப்பும் ஒரு யோசனையில் தொடங்குகிறது, ஒவ்வொரு சுவையான உணவும் ஒரு தீப்பொறியுடன் தொடங்குகிறது.",
    navHome: "முகப்பு",
    navThingMaker: "திங் மேக்கர்",
    navRecipeMaker: "ரெசிபி மேக்கர்",
    navAiAssistant: "AI உதவியாளர்",
    navCollections: "தொகுப்புகள்",
    navAbout: "எங்களை பற்றி",
    myStudio: "எனது ஸ்டுடியோ",
    recipeMakerHeader: "ரெசிபி மேக்கர்",
    recipeMakerSubtitle: "சமையலறை",
    recipeMakerBannerDesc: "உங்கள் கிடைக்கக்கூடிய பொருட்களை அற்புதமான சமையல் கலைகளாக மாற்றுங்கள். எங்கள் AI சேஃப் உங்களிடம் என்ன இருக்கிறது என்பதை புத்திசாலித்தனமாக பகுப்பாய்வு செய்து, சரியான ரெசிபி கலவைகளை பரிந்துரைக்கிறார், மேலும் வெட்டுவதிலிருந்து அழகாக பரிமாறுவது வரை ஒவ்வொரு படியிலும் உங்களுக்கு வழிகாட்டுகிறார்.",
    newRecipe: "புதிய ரெசிபி",
    startCooking: "சமைக்கத் தொடங்குங்கள்",
    aiRecipeGenerator: "AI ரெசிபி ஜெனரேட்டர்",
    getSmartIdeas: "ஸ்மார்ட் யோசனைகள் பெறுங்கள்",
    browsePantry: "பாண்ட்ரி பார்க்கவும்",
    hundredPlusIngredients: "100+ பொருட்கள்",
    aiRecommendedRecipes: "உங்களுக்கான AI பரிந்துரைத்த ரெசிப்பிகள்",
    viewAll: "அனைத்தையும் காண்க →",
    recipeInProgress: "நடந்துகொண்டிருக்கும் ரெசிபி",
    cookingNow: "இப்போது சமைக்கிறோம்",
    continueCooking: "சமைப்பதை தொடர்க",
    ingredientsYouHave: "உங்களிடம் உள்ள பொருட்கள்",
    managePantry: "பாண்ட்ரி நிர்வகிக்கவும் →",
    vegetables: "காய்கறிகள்",
    meats: "இறைச்சி",
    dairy: "பால் பொருட்கள்",
    spices: "மசாலா",
    others: "மற்றவை",
    aiChefAssistant: "AI சேஃப் உதவியாளர்",
    aiChefGreeting: "வணக்கம் சேஃப்! உங்கள் பாண்ட்ரியில் என்ன இருக்கிறது என்பதன் அடிப்படையில் தனிப்பயனாக்கப்பட்ட ரெசிப்பிகளை பரிந்துரைக்கலாம், இல்லாத பொருட்களை மாற்றலாம், மேலும் ஒவ்வொரு படியிலும் வழிகாட்டலாம்.",
    suggestRecipe: "என் பொருட்களுடன் ரெசிபி பரிந்துரைக்கவும்",
    findSubstitute: "முட்டைகளுக்கு மாற்று கண்டறிய உதவுங்கள்",
    pantryOverview: "பாண்ட்ரி மேலோட்டம்",
    mealPlan: "உணவு திட்டம்",
    today: "இன்று",
    tomorrow: "நாளை",
    nutritionInsights: "ஊட்டச்சத்து தகவல்",
    thingMakerHeader: "திங் மேக்கர்",
    thingMakerSubtitle: "பட்டறை",
    thingMakerBannerDesc: "உங்கள் மூலப் பொருட்கள் மற்றும் வீட்டு ஸ்கிராப்பை அற்புதமான, செயல்பாட்டு கண்டுபிடிப்புகளாக மாற்றுங்கள். எங்கள் AI பட்டறை திட்டமிடுபவர் உங்கள் கிடைக்கக்கூடிய கருவிகள் மற்றும் பொருட்களை பகுப்பாய்வு செய்து, பாதுகாப்பு வழிகாட்டுதல்கள், பரிமாண மதிப்பீடுகள் மற்றும் நிபுணத்துவ முடிப்பு குறிப்புகளுடன் விரிவான படிப்படியான திட்ட திட்டத்தை உருவாக்குகிறது.",
    newProject: "புதிய திட்டம்",
    startFromScratch: "புதிதாக தொடங்குங்கள்",
    aiIdeaGenerator: "AI யோசனை ஜெனரேட்டர்",
    getSmartSuggestions: "ஸ்மார்ட் பரிந்துரைகள் பெறுங்கள்",
    importBlueprint: "வரைபடம் இறக்குமதி செய்யவும்",
    requiresPro: "ப்ரோ தேவை",
    aiSuggestedProjects: "உங்களுக்கான AI பரிந்துரைத்த திட்டங்கள்",
    myWorkbench: "என் வொர்க்பெஞ்ச்",
    currentProject: "தற்போதைய திட்டம்",
    continueBuilding: "கட்டுவதைத் தொடர்க",
    projectsBuilt: "கட்டிய திட்டங்கள்",
    inProgress: "நடந்துகொண்டிருக்கிறது",
    ideasSaved: "சேமிக்கப்பட்ட யோசனைகள்",
    materialsInventory: "பொருட்கள் சரக்கு",
    viewAllMaterials: "அனைத்தையும் காண்க →",
    wood: "மரம்",
    metal: "உலோகம்",
    plastic: "பிளாஸ்டிக்",
    electronics: "மின்னணுவியல்",
    aiAssistantWidget: "AI உதவியாளர்",
    aiCreatorGreeting: "வணக்கம் படைப்பாளரே! உங்கள் கண்டுபிடிப்புகளை வடிவமைக்க, திட்டமிட, கட்ட மற்றும் மேம்படுத்த உதவ முடியும்.",
    suggestProjectMaterials: "இந்த பொருட்களுடன் திட்டத்தை பரிந்துரைக்கவும்",
    helpImproveDesign: "இந்த வடிவமைப்பை மேம்படுத்த உதவுங்கள்",
    checkSafetyProject: "என் திட்டத்திற்கான பாதுகாப்பை சரிபார்க்கவும்",
    askAnything: "உங்கள் திட்டத்தைப் பற்றி எதையும் கேளுங்கள்...",
    safetyFirst: "பாதுகாப்பு முதலில்",
    useProtectiveGear: "பாதுகாப்பு கவசம் பயன்படுத்தவும்",
    useProtectiveGearDesc: "வெட்டும்போது, மணல் தடவும்போது அல்லது துளையிடும்போது எப்போதும் பாதுகாப்பு கையுறைகள், கண்ணாடிகள் மற்றும் தூசி முகமூடி அணியுங்கள்.",
    checkToolConditions: "கருவி நிலையை சரிபார்க்கவும்",
    checkToolConditionsDesc: "பயன்படுத்துவதற்கு முன் ஒவ்வொரு கருவியையும் சரிபார்க்கவும். கத்திகள் கூர்மையாக உள்ளதா, கம்பிகள் கிழிந்திருக்கவில்லையா, கைப்பிடிகள் பாதுகாப்பாக உள்ளதா என்று உறுதிப்படுத்திக்கொள்ளுங்கள்.",
    workInSafeArea: "பாதுகாப்பான இடத்தில் வேலை செய்யுங்கள்",
    workInSafeAreaDesc: "உங்கள் பணியிடத்தை நன்கு வெளிச்சமாக, சுத்தமாக மற்றும் சரியான காற்றோட்டத்துடன் வைத்திருங்கள்.",
    viewSafetyGuide: "பாதுகாப்பு வழிகாட்டியைப் பாருங்கள்",
    thingGenTitle: "AI திட்ட வரைபட ஜெனரேட்டர்",
    thingGenDesc: "கீழே உங்கள் கிடைக்கக்கூடிய ஸ்கிராப் பொருட்களை விவரிக்கவும், உங்கள் கருவிகளை தேர்ந்தெடுக்கவும். உங்களிடம் என்ன இருக்கிறது என்பதற்கு ஏற்ப விரிவான, படிப்படியான மறுசுழற்சி திட்ட திட்டத்தை உருவாக்குவோம்.",
    materialsPlaceholder: "உங்கள் பொருட்களை விவரிக்கவும் (உதா., 2 அட்டை பெட்டிகள், 3 பிளாஸ்டிக் பாட்டில்கள், பழைய கம்பி ஹேங்கர்கள்…)",
    selectTools: "உங்கள் கருவிகளை தேர்ந்தெடுக்கவும்",
    generateProject: "திட்ட வரைபடம் உருவாக்கவும்",
    generating: "உருவாக்குகிறது…",
    backToDashboard: "← டாஷ்போர்டுக்கு திரும்பவும்",
    yourMaterials: "உங்கள் பொருட்கள்",
    toolsAvailable: "கிடைக்கக்கூடிய கருவிகள்",
    difficulty: "கஷ்டம்",
    estimatedTime: "மதிப்பிடப்பட்ட நேரம்",
    dimensions: "பரிமாணங்கள்",
    materialsRequired: "தேவையான பொருட்கள்",
    toolsUsed: "பயன்படுத்திய கருவிகள்",
    buildInstructions: "படிப்படியான கட்டும் வழிமுறைகள்",
    safetyGuidelines: "பாதுகாப்பு வழிகாட்டுதல்கள்",
    watchTutorial: "YouTube இல் பயிற்சி பாருங்கள்",
    saveProject: "திட்டத்தை சேமிக்கவும்",
    recipeGenTitle: "AI ரெசிபி உருவாக்குநர்",
    recipeGenDesc: "கீழே உங்கள் சமையலறையில் தற்போது கிடைக்கக்கூடிய பொருட்களின் பட்டியலை செய்யுங்கள். எங்கள் AI சேஃப் உங்கள் பாண்ட்ரியை பகுப்பாய்வு செய்து, சிறந்த சுவை கலவைகளை கண்டறிந்து, முழுமையான ரெஸ்டாரண்ட் தரமான ரெசிபியை உருவாக்குவார்.",
    ingredientsPlaceholder: "உங்கள் பொருட்களை பட்டியலிடுங்கள் (உதா., கோழி, பூண்டு, எலுமிச்சை, ஆலிவ் எண்ணெய், புதிய துளசி, பாஸ்தா…)",
    generateRecipe: "என் ரெசிபியை உருவாக்குங்கள்",
    generatingRecipe: "உங்கள் ரெசிபி தயாராகிறது…",
    prepTime: "தயாரிப்பு நேரம்",
    cookTime: "சமையல் நேரம்",
    totalTime: "மொத்த நேரம்",
    servings: "பரிமாறும் நபர்கள்",
    ingredients: "பொருட்கள்",
    instructions: "படிப்படியான வழிமுறைகள்",
    nutritionInfo: "ஊட்டச்சத்து தகவல்",
    healthScore: "ஆரோக்கிய மதிப்பெண்",
    saveRecipe: "ரெசிபியை சேமிக்கவும்",
    aiAssistantTitle: "AI உதவியாளர்",
    aiAssistantSubtitle: "ஒல்லாமா — உள்ளூர் நுண்ணறிவு",
    aiGreeting: "வணக்கம்! நான் உங்கள் உள்ளூர் AI உதவியாளர். சமையல், சமையலறை மாற்றீடுகள், கைவேலை நுட்பங்கள் அல்லது பொருள் பாதுகாப்பு பற்றி எதையும் கேளுங்கள்!",
    typeMessage: "உங்கள் AI உதவியாளரிடம் கேளுங்கள்…",
    aboutTitle: "கிரியாஃபோர்ஜ் பற்றி",
    aboutDesc: "கிரியாஃபோர்ஜ் உலகின் மிகவும் உள்ளுணர்வு AI-இயக்கப்படும் படைப்பாற்றல் தளம்.",
    ourMission: "எங்கள் நோக்கம்",
    ourTech: "எங்கள் தொழில்நுட்பம்",
    collectionsTitle: "என் தொகுப்புகள்",
    savedRecipes: "சேமித்த ரெசிப்பிகள்",
    savedProjects: "சேமித்த திட்டங்கள்",
    noSavedItems: "இன்னும் சேமிக்கப்பட்ட உருப்படிகள் இல்லை. ஏதாவது அற்புதமானதை உருவாக்குங்கள்!",
    magnifyHint: "மொழிபெயர்க்க உரையின் மேல் வட்டமிடுங்கள்",
    magnifyLabel: "மொழி லென்ஸ்",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    // Update html lang attribute for font rendering
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return (translations[language] && translations[language][key])
      ? translations[language][key]
      : (translations['en'][key] || key);
  };

  const getLanguageName = (code) => {
    return translations[code]?.languageName || code;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageName, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
