export const preloadedThings = [
  {
    id: "solar-desk-lamp",
    title: "Solar-Powered Desk Lamp",
    category: "Electronics",
    difficulty: "Intermediate",
    estimatedTime: "3–4 Hours",
    dimensions: "25cm height × 15cm base",
    levelKey: "Intermediate",
    rating: "4.8",
    reviews: "128",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop",
    materialsRequired: [
      "**1× Small solar panel** (5V, 1W minimum) — salvaged from garden lights or bought cheaply",
      "**1× 18650 lithium battery** — recycled from an old laptop battery pack",
      "**1× TP4056 charging module** — protects battery from overcharge",
      "**3–5× white LED lights** (high brightness, 5mm) — from old fairy lights",
      "**1 metre of thin wire** (insulated, 2-strand) — from salvaged electronics",
      "**1× PVC pipe** (25mm diameter, 20cm long) — or thick bamboo",
      "**1× bottle cap or small plastic disc** — for the lamp shade base",
      "**Hot glue sticks** — for assembly",
      "**Sandpaper** (180 grit) — for finishing",
      "**Black spray paint** (optional, for aesthetics)",
    ],
    toolsUsed: ["Screwdriver", "Scissors", "Hot Glue Gun", "Soldering Iron", "Drill", "Wire Stripper"],
    instructions: [
      "**Plan & Source Components:** Disassemble old solar garden lights (the cheap ones from hardware stores) to harvest the solar panel and often a small rechargeable battery. If unavailable, order a 5V 1W solar panel and a 18650 battery online for under ₹200. Also grab a TP4056 module — it prevents your battery from being overcharged and damaged.\n\n*Pro Tip:* Test your solar panel in sunlight first using a multimeter to confirm it outputs 4–5.5V before building anything.",
      "**Build the Battery Housing:** Take your PVC pipe (20cm length). Drill a 10mm hole at the top side for the wire to exit, and a 25mm slot at the bottom for inserting the battery. Sand all cut edges smooth with 180-grit sandpaper to remove sharp plastic burrs. The battery should slide in snugly — use a thin strip of foam tape around the battery to prevent rattling inside the tube.\n\n*Safety:* Never short-circuit a lithium battery. Keep the terminals apart while working.",
      "**Wire the Charging Circuit:** Solder the solar panel's positive (+) wire to the 'IN+' pad on your TP4056 module, and negative (–) to 'IN–'. Solder the battery's positive terminal to 'BAT+' and negative to 'BAT–'. The 'OUT+' and 'OUT–' pads provide your regulated 4.2V output for the LEDs. Use short wires (5–8cm) to minimise resistance losses.\n\n*Pro Tip:* Wrap all solder joints with electrical tape or heat-shrink tubing to prevent short circuits.",
      "**Build the LED Lamp Head:** Take your bottle cap or plastic disc and mark 3–5 evenly spaced holes using a compass or by tracing around a coin. Drill or heat-punch the holes with a hot nail. Press your LEDs through the holes from the inside — the LED's flat side (cathode) should face down. Wire all LEDs in parallel: connect all positive (longer) legs together, and all negative (shorter) legs together. This keeps the voltage the same as one LED.\n\n*Tip:* Add a 47–100 ohm resistor on the positive wire to limit current and extend LED life.",
      "**Assemble Everything:** Thread the wire up through your PVC pipe from the bottom. Connect the LED head wire to OUT+ and OUT– of the TP4056 module. Glue the solar panel to the very top of the pipe using hot glue (face it upward or at a south-facing angle). Glue the lamp head (LED disc) to the top side of the pipe at a slight downward angle using hot glue and let cure for 5 minutes. Seal all entry points with glue to prevent moisture ingress.\n\n*Dimensions check:* Total height should be ~25cm for a desktop-friendly size.",
      "**Test & Finish:** Place the lamp in direct sunlight for 4–6 hours on day one to fully charge the battery. After charging, shield the solar panel and test the LEDs — they should illuminate automatically in low light (if you've added a light-dependent resistor, LDR) or when you connect the circuit. Spray paint the body matte black for a sleek look. Let paint dry completely (30 minutes minimum) before handling.\n\n*Final check:* Verify no wires are pinched, all joints are insulated, and the lamp base is stable. Enjoy free light!"
    ],
    safetyGuidelines: [
      "**Battery Safety:** Never puncture, crush, or expose 18650 batteries to temperatures above 60°C — this can cause thermal runaway and fire. Always use the TP4056 protection circuit.",
      "**Soldering Safety:** Work in a ventilated area. Solder fumes are harmful — use a small fan to blow fumes away from your face. Keep soldering iron in its stand when not in use.",
      "**Electrical Safety:** Double-check polarity (+ and –) before connecting power. Reversed polarity can instantly destroy your TP4056 module.",
      "**Hot Glue Burns:** The glue nozzle reaches 200°C. Never touch it directly. Keep a bowl of cold water nearby for accidental skin contact.",
    ],
    youtubeSearchQuery: "solar powered desk lamp DIY build from scratch tutorial",
  },

  {
    id: "automatic-plant-waterer",
    title: "Automatic Plant Waterer",
    category: "Robotics & Garden",
    difficulty: "Beginner",
    estimatedTime: "1.5–2 Hours",
    dimensions: "Bottle: 500ml–1L, Wick: 30cm",
    levelKey: "Beginner",
    rating: "4.7",
    reviews: "93",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&auto=format&fit=crop",
    materialsRequired: [
      "**2× plastic bottles** (500ml or 1L) — one as water reservoir, one as pot cover",
      "**1× cotton rope or shoelace** (30–40cm) — natural cotton wicks water best",
      "**1× small pot** with drainage hole — or a recycled tin can",
      "**Potting soil** — any standard mix",
      "**Sharp needle or heated nail** — for making holes",
      "**Waterproof tape** (electrical or duct tape) — for sealing",
      "**String or wire** — for hanging the reservoir bottle if desired",
    ],
    toolsUsed: ["Scissors", "Utility Knife", "Needle", "Tape Measure"],
    instructions: [
      "**Prepare the Wick:** Cut a 30–35cm length of cotton rope or natural shoelace. Avoid synthetic materials — they repel water. Wet the wick completely in water and squeeze out excess so it's damp but not dripping. This 'primes' the cotton fibres, allowing capillary action to start immediately. Thread one end 8–10cm through the bottle cap's centre hole (make the hole with a heated needle — slightly smaller than the rope diameter so it grips tight).\n\n*Science behind it:* Cotton fibres draw water upward against gravity through capillary action — the same way plants draw water through their roots.",
      "**Set Up the Water Reservoir:** Fill a 500ml or 1L bottle with clean water. Screw the modified cap (with wick threaded through) tightly onto the bottle. Invert the bottle — water should NOT pour out freely. If it does, your wick hole is too large; wrap the wick with tape to create a tighter seal. The water will only flow as the soil dries and creates a slight vacuum, drawing water through the wick.\n\n*Pro Tip:* Add a small pinch of liquid fertiliser to the water for a slow-release feeding system.",
      "**Prepare the Plant Pot:** Fill your pot 80% with potting soil. Push your finger 3–4cm deep into the centre of the soil to create a channel. Thread the dry end of the wick down through this channel, burying it in the soil so 8–10cm of wick is surrounded by soil. The buried portion is what delivers water to the plant roots. Pack soil gently around the wick to ensure good contact.\n\n*Placement tip:* The wick end buried in soil should ideally be near where the roots are most concentrated — roughly at the centre-bottom of the pot.",
      "**Position the Reservoir:** Place the inverted bottle directly on top of the soil surface, or use string/wire to hang it at the same height as the pot. The wick running from bottle cap down into the soil creates the continuous feed loop. For tabletop use, cut the bottom of the bottle off (it's now inverted, so the cut-off bottom becomes an opening to refill — just lift, top up, and re-invert). Leave a 1–2cm air gap at the neck between bottle and soil for airflow.\n\n*Refill frequency:* A 500ml bottle lasts 7–14 days depending on plant size and ambient temperature.",
      "**Test & Calibrate:** Check the system 24 hours after setup — the soil should feel evenly moist but not waterlogged. If too wet: raise the bottle slightly (reduces water flow). If too dry: lower it or try a thicker wick. Test by pressing your finger 2cm into the soil — it should feel like a wrung-out sponge. Once calibrated, this system runs itself for 1–2 weeks. Perfect for holidays!\n\n*Decoration idea:* Wrap the reservoir bottle with twine or paint it with acrylic paint to make it look like a decorative planter accent."
    ],
    safetyGuidelines: [
      "**Over-watering Risk:** Test the system for 48 hours before leaving on a long trip. Different plant species have vastly different water needs — succulents need far less than ferns.",
      "**Mould Prevention:** Clean the water reservoir bottle weekly with a diluted vinegar rinse if you notice any green algae growth.",
      "**Bottle Stability:** Ensure the inverted bottle is stable and cannot tip over onto the plant, which could damage the stem.",
    ],
    youtubeSearchQuery: "automatic self watering plant system DIY plastic bottle capillary wick",
  },

  {
    id: "cardboard-desk-organizer",
    title: "Modular Cardboard Desk Organizer",
    category: "Home & Office",
    difficulty: "Easy",
    estimatedTime: "1.5 Hours",
    dimensions: "30cm × 20cm × 15cm (customisable)",
    levelKey: "Beginner",
    rating: "4.9",
    reviews: "157",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&auto=format&fit=crop",
    materialsRequired: [
      "**3–4 large cardboard boxes** — double-corrugated is strongest (appliance/shoe boxes ideal)",
      "**White school glue or PVA glue** — creates a strong, hard bond when dry",
      "**Decorative paper or washi tape** — for covering exposed cardboard edges",
      "**Acrylic paint** (optional) — 2 colours for a layered look",
      "**Ruler and pencil** — for precise marking",
      "**Cutting mat or thick newspaper** — protect your work surface",
    ],
    toolsUsed: ["Scissors", "Utility Knife", "Ruler", "Glue Gun", "Paintbrush"],
    instructions: [
      "**Design Your Layout:** Sketch your organiser on paper first. Decide on compartment sizes based on what you'll store: tall narrow slots for pens/pencils (4cm wide × 12cm tall), wider slots for notebooks (15cm wide), a shallow tray for paper clips. The beauty of modular design is each compartment is built separately then assembled. Label your sketch with measurements.\n\n*Modular advantage:* If one compartment breaks later, you replace only that piece, not the whole unit.",
      "**Cut the Cardboard Panels:** Using a ruler and pencil, mark all panels on your cardboard. Use a sharp utility knife against a metal ruler for perfectly straight cuts — never scissors for structural panels (they compress the corrugation and weaken it). For each rectangular compartment you need: 2 long sides, 2 short sides, and 1 base (5 pieces total). Cut on a cutting mat or thick stack of newspapers to protect your surface.\n\n*Pro Tip:* Stack-cut identical pieces: layer 3 sheets of cardboard and cut all at once for perfectly matched dimensions.",
      "**Reinforce All Panels:** Single-layer cardboard warps and bends. Glue 2–3 layers of cardboard together for every panel, alternating the corrugation direction (one layer horizontal corrugation, next layer vertical). This cross-lamination technique creates a material as stiff as lightweight plywood. Apply PVA glue between layers, stack, and place under heavy books for 20 minutes while it dries.\n\n*Why this works:* Cross-laminated cardboard is the same principle as cross-laminated timber (CLT) used in modern architecture.",
      "**Assemble the Compartments:** Apply hot glue to the inside edge of each side panel and press the base on firmly, holding for 30 seconds. Then glue side panels to each other. For extra strength, run a thin bead of PVA glue along every interior joint after the hot glue cures — PVA creates a harder, longer-lasting bond. Use binder clips to hold joints while PVA dries (15–20 min). Check each compartment is square using a set square or the corner of a book.\n\n*Technique:* Build a square jig from spare cardboard to hold compartments at 90° while glue dries.",
      "**Assemble the Final Structure:** Once individual compartments are dry, arrange them in your planned layout. Hot-glue compartments to each other at their shared walls. Add a backing panel (single layer of cardboard) glued across the entire rear to tie everything together and dramatically increase rigidity. The backing panel should be the exact overall width and height of your assembled organiser.\n\n*Finishing:* Sand exposed cardboard edges gently with 220-grit sandpaper for smooth edges before painting or covering.",
      "**Decorate & Seal:** Apply 2 coats of gesso (white primer) or diluted PVA to all surfaces — this seals the cardboard and prevents paint from being absorbed unevenly. When dry, paint with acrylic colours of your choice. Once fully dry (1 hour), apply 2 coats of Mod Podge or clear acrylic sealer to protect the surface from moisture and daily wear. Alternatively, wrap sections with washi tape for a quick, no-paint finish.\n\n*Tip:* Decoupage newspaper pages for a vintage aesthetic — apply PVA over the paper as both adhesive and sealer."
    ],
    safetyGuidelines: [
      "**Knife Safety:** Always cut away from your fingers. Keep the blade sharp — a dull blade requires more pressure and is more likely to slip.",
      "**Fume Ventilation:** Use spray paint and solvents in a well-ventilated area or outdoors.",
      "**Hot Glue:** Allow the glue gun to cool to 'warm' setting if available — this is sufficient for cardboard and reduces burn risk.",
    ],
    youtubeSearchQuery: "DIY cardboard desk organizer modular step by step easy craft",
  },

  {
    id: "bluetooth-speaker",
    title: "DIY Bluetooth Wooden Speaker",
    category: "Electronics & Audio",
    difficulty: "Intermediate",
    estimatedTime: "4–5 Hours",
    dimensions: "20cm × 10cm × 8cm",
    levelKey: "Intermediate",
    rating: "4.6",
    reviews: "112",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&auto=format&fit=crop",
    materialsRequired: [
      "**1× Bluetooth audio module** (PAM8403 or XY-BT-Mini) — ₹150–300 online",
      "**2× small speakers** (3W, 4-ohm) — salvaged from old radios or bought cheaply",
      "**1× USB power bank** (5V 2A, old one works) — or rechargeable 18650 + TP4056 module",
      "**1× piece of 12mm plywood or MDF** (30cm × 20cm) — or solid wood offcut",
      "**Speaker cloth or mesh fabric** — for the grille (old speaker or bought by the metre)",
      "**M3 screws** (8mm length) — for securing electronics",
      "**Sandpaper** (120, 220, 400 grit) — for progressive wood finishing",
      "**Wood stain or oil** — for a premium finish",
      "**Hot glue + Wood glue** — for assembly",
    ],
    toolsUsed: ["Handsaw", "Drill", "Screwdriver", "Sandpaper", "Paintbrush", "Glue Gun"],
    instructions: [
      "**Cut the Enclosure Panels:** Mark and cut 6 panels from your 12mm plywood: top (20×10cm), bottom (20×10cm), 2 sides (8×10cm), front (20×8cm minus speaker holes), back (20×8cm with a cable access hole). Use a handsaw for straight cuts or take your marked plywood to a hardware store for machine cutting (often free or cheap with purchase). Sand all panels to 120-grit immediately after cutting to remove saw marks.\n\n*Acoustic tip:* The internal volume of your box directly affects bass response. This 1.6-litre box is tuned for small 3\" speakers. Don't deviate more than 20% from these dimensions.",
      "**Cut Speaker Holes in the Front Panel:** Using a compass, mark 2 circles on the front panel — each circle's diameter should be 5mm smaller than your speaker's total diameter (not cone diameter). This creates a lip that supports the speaker frame. Cut the circles using a jigsaw or drill a starter hole and use a coping saw. Test-fit your speakers — they should sit flush with a slight lip all around. Mark and drill 4 small screw holes around each speaker position.\n\n*Pro Tip:* Cut a thin gasket ring from foam tape and place between the speaker and wood panel — this improves the acoustic seal dramatically.",
      "**Assemble the Wood Enclosure:** Apply wood glue to all mating edges. Assemble in this order: glue bottom to back panel first, then add the two side panels, then the front panel (without speakers yet), and finally the top. Use corner clamps or binder clips to hold joints at 90° while glue cures (30–45 minutes minimum). After curing, reinforce all interior corners with a small bead of hot glue for airtightness — this is critical for speaker performance.\n\n*Why airtight matters:* Air leaks cause the speaker to lose bass efficiency. Every gap in the enclosure loses acoustic pressure.",
      "**Wire the Electronics:** Connect speaker wire (red = +, black = –) from the Bluetooth module's L-OUT and R-OUT terminals to each speaker. If using PAM8403: VCC to 5V, GND to ground, audio inputs to the Bluetooth module's audio output. Keep wire runs as short as possible — excess wire inside the cabinet can buzz against the enclosure. Wrap all connections with electrical tape or use heat-shrink tubing. Thread wires through a small hole (6mm) in the back panel, leaving the USB input accessible from outside.\n\n*Test before sealing:* Connect power and play music before gluing the back panel — confirm both speakers work and audio is clear.",
      "**Mount Electronics & Seal:** Use M3 screws to mount the Bluetooth module to the inside back panel using small standoffs (a folded piece of cardboard works as a temporary standoff). Screw the speakers into their holes from the front panel using M3 screws through the pre-drilled holes. Attach the power bank inside using double-sided foam tape — it should be accessible through a removable back panel (held with 2 screws) for recharging. Seal the main enclosure with wood glue on the last panel.\n\n*USB port:* Drill a precisely sized hole in the back panel for the USB charging cable to pass through.",
      "**Sand & Finish the Wood:** Progressive sanding is the secret to a premium finish. Start with 120-grit (removes roughness), then 220-grit (smooths), then wet-sand with 400-grit (ultra-smooth). Between coats of finish, always lightly sand with 400-grit. Apply your chosen finish: wood oil (natural, waterproof, easy — 2–3 coats with 4-hour drying between coats), wood stain + polyurethane varnish (richer colour, 2 stain coats + 2 varnish coats), or just pure tung oil for a beautiful hand-rubbed look.\n\n*Speaker grille:* Cut speaker cloth 2cm larger than the front face. Stretch it taut and staple/glue to the rear of the front panel before final assembly for a professional, flush grille look."
    ],
    safetyGuidelines: [
      "**Lithium Battery Safety:** If using 18650 batteries internally, ensure the TP4056 protection circuit is used — without it, overcharging can cause fire.",
      "**Woodworking Safety:** Wear safety glasses when sawing. Sawdust is a respiratory irritant — work outdoors or wear an N95 dust mask.",
      "**Electrical Safety:** Disconnect all power before making wiring changes. Never work on live circuits.",
      "**Soldering:** Use in a ventilated area. Solder fumes from flux contain irritants.",
    ],
    youtubeSearchQuery: "DIY wooden Bluetooth speaker from scratch complete build tutorial",
  },
];
