export const TOOLS_AND_MATERIALS = [
  "Hammer", "Screwdriver (Phillips)", "Screwdriver (Flathead)", "Pliers",
  "Needle-Nose Pliers", "Wrench", "Adjustable Wrench", "Allen Keys (Hex Keys)",
  "Tape Measure", "Ruler", "Level", "Utility Knife", "Scissors", "Handsaw",
  "Hacksaw", "Coping Saw", "Power Drill", "Drill Bits", "Screws", "Nails",
  "Nuts & Bolts", "Washers", "Sandpaper", "Sanding Block", "Wood Glue",
  "Super Glue", "Hot Glue Gun", "Hot Glue Sticks", "Duct Tape", "Masking Tape",
  "Painter's Tape", "Double-Sided Tape", "Zip Ties", "Twine", "Rope", "Wire",
  "Wire Cutters", "Wire Strippers", "Soldering Iron", "Solder", "Multimeter",
  "Electrical Tape", "Batteries (AA/AAA/9V)", "Battery Holder", "LEDs",
  "Resistors", "Capacitors", "Transistors", "Switches", "Arduino Board",
  "Breadboard", "Jumper Wires", "Motors (DC)", "Servo Motors", "PVC Pipe",
  "PVC Fittings", "Cardboard", "Cardboard Tubes", "Paper", "Construction Paper",
  "Popsicle Sticks", "Toothpicks", "Wooden Dowels", "Plywood Scrap",
  "MDF Scrap", "Pallet Wood", "Plastic Bottles", "Plastic Containers",
  "Aluminum Cans", "Tin Cans", "Glass Jars", "Styrofoam", "Foam Board",
  "Fabric Scraps", "Needle and Thread", "Pins", "Rubber Bands",
  "Paper Clips", "Binder Clips", "Stapler", "Staples", "Paint Brushes",
  "Acrylic Paint", "Spray Paint", "Markers", "Pencils", "Eraser",
  "Chalk", "Chalkboard Paint", "Varnish / Sealant", "Epoxy Resin",
  "Safety Goggles", "Work Gloves", "Dust Mask", "Ear Protection",
  "Clamps (C-Clamps)", "Spring Clamps", "Vise", "Workbench", "Pegboard",
  "File Set", "Chisels", "Mallet", "Pry Bar", "Staple Gun", "Measuring Square",
  "Stud Finder", "Flashlight", "Extension Cord", "Safety Pins", "Rubber Cement",
  "Contact Cement", "Spackle", "Putty Knife", "Caulk", "Caulking Gun"
];
